# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-check
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 10 # if a job hasn't starting in this many seconds, skip
  concurrencyPolicy: Forbid # either allow|forbid|replace
  successfulJobsHistoryLimit: 3 # how many completed jobs should be
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: example-check
          containers:
          - name: example-check
            image: registry.sighup.io/poc/example-check:unstable
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: tbd-envs
          restartPolicy: OnFailure
